sudo: false
language: clojure
lein: 2.8.1
jdk:
  - oraclejdk8
  - oraclejdk9

env:
  global:
    # Encrupted WHITESOURCE_TOKEN for updating Whitesource licensing information
    - secure: "vmRjdv44PcPSyg1durtf5c4t1tzS+OZFegl0oliO0B+ENL4zF7JVxQAZoyLPuLLgBVwfUI3+JQ3CJZdr94/Bvywm+d/N9WMQDtlm23CpefBb5k4nsc/QoKpEAe4wS7BdZKyw4Jas9kKWsXaAg9l3/ACTDxiuztKOnV/4CpxazCytDLGD465U2SCsMMTqiKvFuJrfSt7KruCa8Rh5Z5D4lIT2zhJcJyiYS9IyJ2Ow3cslm2TSRIIgkKE4b81FuC3ng+Rd59WzLJjkI/pTJM3fUolF8T8xPTMfvy//LSWFutCCy9wXzPPaqx7Y99DknpPERFin43orIMhBTaop3O/r1FSJ0od8esvfgs7T08E9q+Q1j4zWYin4L31rKBJpMNpNXMN3EUMoo9kQaqV0tLnzfntxXV2/yBdQuYHBciAu0q7Hlw8Cy32Yb02tagv5oaPthHiloJimHcKVUIzPe1/dggzHEor58SL0ovE4bwzuLOWfFIH6YGg33rklhjEjdifv0Bz//eo4dUUIKKj60CF1DKg3xvdPAMmPHqGGzJunaZHrSo97NSHWFvUYp/wa0V9b1X80bD+Xtp7frXicqiAXaQK3rHne9vKTEgMj4VAGOJLIxDwAssQFnOqG15oW4D/2zrzLmCZN+NQVJuiJ+31C65xa8HO9ReX7jyaKUXCvGbM="
    # Encrypted CLOJARS_USERNAME for Clojars deployment
    - secure: "gqREOzwNqQ4IMLLG3YInGep8xP0Rmj3iiNYoss6oLcQQ9CQvJ0CW5Nqh7hbTl6DuJ4YLtn5eKnQvHmkUyQ+CfTesJnl27Cbc2xvaNEjGXVGE4YQfywpyxAZ0TReAULhEvPE8OvdU3bBy3AKzwqH6bsgKOIqDepG+YKjfnSVS7+YdE7ptGal+NU0Yc4xzKkRQxgKNZsM5AWoTMNqvSq6y7O5qTtBtOO9LZFvDiLi9B99GAibKGFjIAXamtmnF19Zu3e9eD/Lf6Vq9WCfxwkL3b+ScLqNgScBpek5fm00rvYdHSOpu9LgV73n3ZIaomlMaduta35UhIM25AeFwvTnNt2pB8BkIg2jEL5Zhjj0NSEs18Wru2hyWN8rQm2Tw0GibOhXE6kJHjEd9VVgnwRKVViO4y9/VPC5+IzU59Es8a1A5ekn2sLzQyL+kvnc9o5gJOGVlPSt8rD7+Si3Pbr/1cAciGBCeA98X/oRTeg8gE3t93a+27pp4Tmv/88GDmuSRQ02BmCfNGcZ/1qh9jtjEtRYbakbmhMjffObOAlhjNM9lZBAXp+Fj1yTQwOBoXc3+g/1m602WWbvcDiI8fuICoXbVSAjePYHgPKhYTFJYD8/DbWW+VtVtXRuxzFCYTXv11ykIQkdfv3f0kY7i+Grddg7G7KL11TRIDDSlEhFpR6I="
    # Encrypted CLOJARS_PASSWORD for Clojars deployment
    - secure: "sVS4mSGa1wbixv86GTop/i42Dd7wywWdw064TXhdxWhiFSRxe/v3nwnTRCNxqX7uAfcrLP/ov8N6gaV7Qe22KBNhp5ADhjsRhY81gCcdowHDIAemiLX/xaQgfgqD5zPLarvXlpxDVTzu0e26SE9FDWBLMphKiGeQL/84D/1PEe1r85exiI2pBxrLfDXW57LPYTJJnwqkZni8dmbmzDwvPXuh3qqBCG5mwKJhJnSTiat9XYvl1mBUhFvqyNkrIJr0Qd1uIBqfzuxSUCsiJ6R3Ebs7V9IDiw+sp80ggInYLttmGL/Ug9ihhZ6vRl2joWLwF6JjDG5I6xnYfHtHpQ6vfw6Ao1WI7olHq1Kff6909Dwgvx6nOi2mxZqXK6mdRNTx59eVmNNPCybNZVOH1kkO9Z/UfmNsjJl/5atfgVOd2Z9PImXU/45x3PtfQQbEmZygRp8vx5oPNctfp5jEEE1ibA/rw52qaB7sfTzUE8k4NTioWWOMx6L8qUU0zZzK6szB2QIUbrL7z8TZDA6rguUTC3k/R0hjG3Y2eE52IMzTH9Hd1zX2FCIM4Z6CV+aZIdHuzoX7go82NPfuVTHkoMN21UiHT2AxNPuJ6RvbwWo6BGX5zlguCbuqBMBHiaNqUrm4f7AONKt8DRiKIZSqhz+5DWNjZlNGcNOUhJJjUptoczU="
    # Encrypted GITHUB_TOKEN for gh-pages deployment
    - secure: "DyEoEUrxq3axPX6cX1zUqgdlcpXtA8YG56QuNWtFRtAIwYwyAe47owUQJrAFHFPNmuLUhAlQnC9Lb+MzkR187dsKLoNb4/mJP50PZdPqDAo1XYZIfZXQc6CXjq0UV4B1I2P2TKnur5QcIk5SaFuoePzqudyow1c0b8PHg9jLb6U5NPUs4bzVQ0ntuqok+5IiHKsS2xUUGn1jRYSYUZkEQDjya9XOFW+7hPbGaSb3n7c1a/CbsTeRW0mxHWxMwm8qMF7up9s+ApByqqWVnTng+ce+qYaoMNAQDHe+Sp3A7E2tnwK61qvlsbiYij8FP+MLURBijcrshcheDHikl5NhOZofrD0Bgx+PWtzyOeAcIZ38Ubqx6SYbYHkKnms+btRn0p7F+ClKDThebPcnFvlQWnUTLhVjXPQqIOBQOjOtmmE3eD2dAREcbre0mzLKObGa+IscZZ72rqtzSNyzDcgyqyzg/wYqw7POefGngI6y6qOsRHwrMRhAKx5A238KHgH4Wh3H1sgiwxsF7P0HGqmPGes9F65mzF3fV3el8HGsjE3oMYhViImyhiN37ONE1rDfuL6f0VGnZFDkV4zP7tySq+UKThjCkGmXhmrP2gHo6n8LDiA4tD0VMmSY4Hn8l8wbIYTlMMgVX5wisQ8Cy6vSZfBNcVR/WNpOoh4644W6isA="

script: lein check

after_success: lein pom && mvn org.whitesource:whitesource\-maven\-plugin:3.3.1:update -Dorg.whitesource.orgToken=$WHITESOURCE_TOKEN -Dorg.whitesource.ignoredScopes=test,runtime,provided,system

deploy:
  # Deploy binaries to Clojars
  - provider: script
    skip_cleanup: true
    script: lein deploy
    on:
      branch: master
  # Generate documentation
  - provider: script
    skip_cleanup: true
    script: lein codox
    on:
      branch: master
  # Deploy documentation
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    email: travis+clj-symphony@symphony.foundation
    name: Travis CI - Symphony Software Foundation
    local_dir: target/doc
    on:
      branch: master
